### ISSUE TITLE
HTTP 207 Response leads to Errors though actions are performed correctly 

### ISSUE THREAD

**Issue by peer69** [jensweigele/ioBroker.yahka#108]
I recently received errors when controlling accessories with Siri. I filed an apple bugreport but the response indicated there is something wrong with the status reply the yahka adapter sends. 

This is my original bug report decription: 

> When I use Siri to control HomeKit Accessories Siri replies with an Error Message (german: "tut mir leid da ist was schief gelaufen Bitte versuche es noch mal"). This issue occured only on one HomePod at the beginning. After trying to trobleshoot this Issue occurs now on both HomePods I have. For HomePods this issue is completely reproduceable and occurs every time an accessory or a group of accessories is controlled. 

After providing diagnosis data I received the following response. It mentions homebridge but the reply seems to come from the yahka adapter: 

> The issue is on the HomeBridge hub. The hub is sending back a HTTP 207 even though actions were successful with a status 0 indicating a failure.  Since HomeBridge is not officially HomeKit certified we cannot follow up on this with the vendor.   Please understand, the issue is on the accessory side and the vendor not being an official HomeKit certified vendor there is not much that can be done here to follow up.  You will need to contact the vendor.  
> 2019-03-05 21:58:06.913075+0100 localhost homed[65]: (HomeKitDaemon) [com.apple.HomeKit:Siri] Incoming Siri command(840b3bad-ba1d-48e8-8000-c3f413f004cd) serverValidity 42:292: filter: homeName=Zu Hause;zoneName=Erdgeschoss;entityType=SERVICE;serviceType=LIGHTBULB; serverValidity=42:292; actions: [0]: actionType=SET;attribute=POWER; value=BooleanValue=NO;;   
> 2019-03-05 21:58:06.928852+0100 localhost homed[65]: (CoreHAP) [com.apple.HomeKit:default] [IP Accessory Server HBSNEW-2F42 CF:71:4D:D3:C6:32] Sending PUT request to '/characteristics' with body    
> 2019-03-05 21:58:06.942003+0100 localhost homed[65]: (CoreHAP) [com.apple.HomeKit:default] [IP Accessory Server iobyahka-198E c1:5f:a3:a1:35:2a] Characteristic write request responded with '207 Multi-Status' HTTP status code { characteristics = ( { aid = 34; iid = 10; status = 0; }, { aid = 35; iid = 10; status = 0; } );

**Comment by schmdt** [comment]
Uuuuh I thought something is wrong with my personal setup, but obviously not. I’m getting the exact same message from my HomePod, though it only happens when interacting with my TRÅDFRI bulbs which are handled directly by the TRÅDFRI gateway, without iobroker/yahka being in the middle. I even haven’t set up any TRÅDFRI devices in yahka at all. 

I’m furthermore just getting the error when using Siri on HomePod, not when using siri on iPhone/watch. 

I tend to say apple has changed something on the HomePod side. 

@peer69 can you confirm this not happening on other apple devices besides your homepods?

**Comment by peer69** [comment]
I have this issue using a HomePod or an Apple Watch. Didn’t happen using an iPhone yet.

**Comment by schmdt** [comment]
I've done a little research. Obviously this problem is not directly related to yahka, nor to ioBroker at all. The problem was reported for Hue, Tradfri, Eve and various other devices.

See:
* https://forum.smartapfel.de/forum/thread/2953-siri-antwortet-tut-mir-leid-irgendetwas-stimmt-da-nicht-macht-es-aber/
* https://www.reddit.com/r/HomeKit/comments/avore3/siri_works_on_the_watch_while_saying_that_theres/
* https://communities.apple.com/de/thread/250178559?page=2
* ...

Apple always suggests resetting the affected device, the affected HomeKit Gateway (ATV/HomePod), the whole HomeKit "House" and so on. In the end, they are always pretending the issue to be on the vendors side.

Imho, the problem is apple's. I've found a posting stating that only devices with iOS 12.1.3 (which is the latest on HomePod) are affected, while upgrading to 12.1.4 fixes the issue. That said, all my devices (except the homepod) are running on the latest minor release, which obviously is not affected, thus working fine. 

🤷‍♂️

**Comment by peer69** [comment]
Not sure what fixed my problem but it seems to be solved. Looking at the debug log I received from apple it seemed that the 207 repsonse came from yahka. Thats why I didn't doubt apple. Anyway, whatever fixed the error, let's hope it doesn't come back.
