### ISSUE TITLE
YAHKA crashes continouesly when using home app

### ISSUE THREAD

**Issue by derfritz1** [jensweigele/ioBroker.yahka#160]
Hi there.
I'm using YAHKA prefer redly to map my KNX Installation to HomeKit using iobroker and the KNX adapter. Initially, with Version 0.8.1 it worked fine. After upgrading to 0.9.2 it continuesly crashes when pressing a "button" in the home app, i.e. to switch a light. The Adapter restarts after that.

I suspected the knx adapter that was updated as well, but I have no option to downgrade, due to the knx architecture and importing projects. As well I need the multistage feature due to the knx architecture, where state and action are typically two objects.

I get this error log:

`

host.iobroker | 2020-01-27 20:16:09.980 | info | Restart adapter system.adapter.yahka.0 because enabled
-- | -- | -- | --
host.iobroker | 2020-01-27 20:16:09.979 | info | instance system.adapter.yahka.0 terminated with code 0 (NO_ERROR)
host.iobroker | 2020-01-27 20:16:09.979 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:68:7)
host.iobroker | 2020-01-27 20:16:09.978 | error | Caught by controller[0]: at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
host.iobroker | 2020-01-27 20:16:09.978 | error | Caught by controller[0]: at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.iobroker | 2020-01-27 20:16:09.977 | error | Caught by controller[0]: at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:572:33)
host.iobroker | 2020-01-27 20:16:09.976 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:2694:37
host.iobroker | 2020-01-27 20:16:09.975 | error | Caught by controller[0]: TypeError: Cannot read property 'val' of null
yahka.0 | 2020-01-27 20:16:09.441 | info | (1292) Terminated (NO_ERROR): Without reason
yahka.0 | 2020-01-27 20:16:09.437 | info | (1292) terminating
yahka.0 | 2020-01-27 20:16:09.423 | info | (1292) cleaned up ...
yahka.0 | 2020-01-27 20:16:09.421 | info | (1292) cleaning up ...
yahka.0 | 2020-01-27 20:16:09.417 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
yahka.0 | 2020-01-27 20:16:09.417 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
yahka.0 | 2020-01-27 20:16:09.417 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
yahka.0 | 2020-01-27 20:16:09.417 | error | at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:572:33)
yahka.0 | 2020-01-27 20:16:09.417 | error | at /opt/iobroker/node_modules/iobroker.yahka/main.js:2694:37
yahka.0 | 2020-01-27 20:16:09.417 | error | (1292) TypeError: Cannot read property 'val' of null
yahka.0 | 2020-01-27 20:16:09.415 | error | (1292) uncaught exception: Cannot read property 'val' of null
yahka.0 | 2020-01-27 20:16:02.591 | info | (1292) adding Flur with UUID: 1a420c78-9de5-419a-92b2-c3b22c973b43
yahka.0 | 2020-01-27 20:16:02.572 | info | (1292) adapter ready, checking config
yahka.0 | 2020-01-27 20:16:02.486 | info | (1292) starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.yahka, node: v10.18.1

`

Any idea? Thank you! 

Fritz

**Comment by derfritz1** [comment]
I hav an Update regarding that issue:

For some reason the adapter does more likely not crash when I configure a service as "state", try it, and then change it to "multistate". Using this procedure, it works for some reason...

**Comment by nicoh88** [comment]
@derfritz1 

Du hast dein Problem scheinbar gelöst.
Könntest du es dennoch noch einmal, für die Community genauer erklären - natürlich auch deine Lösung!

DANKE

**Comment by DanielWeeber** [comment]
Sieht mir eher nach einer falschen/invaliden Eingabe von States bei einem Service aus.

**Comment by cryptedx** [comment]
Ich hab auch exakt dasselbe Problem und nutze ebenfalls KNX. Ich muss dementsprechend MultiState verwenden. Komischerweise hat das Dimmen eines Lichtes einwandfrei funktioniert und dann später nicht. Bin auf Version 0.11.0. Auf NodeJS 12.18.3 und 12.18.4 getestet. Hatte gehofft, dass eine update hilft.

Ich hab festgestellt, dass nachdem ich den Dienstnamen von "EG Gast Licht Decke Dimmen" auf "Dimmen" geändert habe, dass es dann gecrashed ist. Nun habe ich die Änderung revidiert und es geht wieder. Das kann aber auch nur ein Zufall oder eine Nebenerscheinung sein.
Da "EG Gast Licht Decke Dimmen" nun funktioniert, gehe ich nun ans Licht vom Gästebad (nur Schalten). Ich habe ein anderes Gerät dupliziert, welches mit MultiState konfiguriert war. Wieder ein Absturz beim Schalten in der Home App.
Nächster Versuch mit nur "State". Es funktioniert! Ich gehe wieder über zu MultiState. Es funktioniert wieder!

Nun geht es an die Küche. Dort ebenfalls nur schaltbar. Ich habe nun das Licht vom Gästebad dupliziert. Es funktioniert auf Anhieb.
Ich dupliziere wieder von "EG Gast Licht Decke Dimmen" und vergesse "Gast" zu "Wohn" umzubenennen beim Dienstnamen. Yahka crached wieder. Gerät gelöscht und erneut dupliziert wie davor und korrekt benannt. Es funktioniert. Dann schreibe ich das hier und sehe in meiner App das yahka von allein gecrashed ist bei dem neuen Gerät. Jetzt geht es wieder nicht. Was ist da los? :-)

Nun habe ich das gemacht von MultiState ausgehend => State => Speichern => MultiState => speichern. Es geht wieder. Das scheint dann wohl der Vorgang gewesen zu sein von @derfritz1 
Ich schreibe das hier und sehe in meiner App das yahka wieder von allein gecrashed ist. Meine Güte.

Wie kann ich weiter helfen?!

Eine komische Nebenerscheinung ist, dass das Licht als dimmbar eingestellt ist obwohl man es nur schalten kann. Ich habe es aber unter "On" konfiguriert. Wie kann das sein?


yahka.0 | 2020-09-22 22:09:39.248 | error | (23093) TypeError: Cannot read property 'val' of null at /opt/iobroker/node_modules/iobroker.yahka/main.js:2600:37 at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis
-- | -- | -- | --
yahka.0 | 2020-09-22 22:09:39.229 | error | (23093) uncaught exception: Cannot read property 'val' of null

host.raspberrypi | 2020-09-22 22:09:39.843 | error | Caught by controller[14]: Tue, 22 Sep 2020 20:09:39 GMT EventedHTTPServer [::ffff:192.168.1.51] Sending HTTP event '22.11' with data: {"characteristics":[{"aid":22,"iid":11,"value":30}]}
-- | -- | -- | --
host.raspberrypi | 2020-09-22 22:09:39.842 | error | Caught by controller[13]: Tue, 22 Sep 2020 20:09:39 GMT EventedHTTPServer [::ffff:192.168.1.51] Sending HTTP event '22.11' with data: {"characteristics":[{"aid":22,"iid":11,"value":11}]}
host.raspberrypi | 2020-09-22 22:09:39.842 | error | Caught by controller[12]: Tue, 22 Sep 2020 20:09:39 GMT EventedHTTPServer [::ffff:192.168.1.51] Muting event '22.10' notification for this connection since it originated here.
host.raspberrypi | 2020-09-22 22:09:39.842 | error | Caught by controller[11]: Tue, 22 Sep 2020 20:09:39 GMT Accessory [Yahka-0] Setting Characteristic "On" to value 1
host.raspberrypi | 2020-09-22 22:09:39.841 | error | Caught by controller[10]: Tue, 22 Sep 2020 20:09:39 GMT Accessory [Yahka-0] Setting Characteristic "Brightness" to value 100
host.raspberrypi | 2020-09-22 22:09:39.841 | error | Caught by controller[9]: Tue, 22 Sep 2020 20:09:39 GMT Accessory [Yahka-0] Processing characteristic set: [{"aid":22,"iid":11,"value":100},{"aid":22,"iid":10,"value":1}]
host.raspberrypi | 2020-09-22 22:09:39.840 | error | Caught by controller[8]: Tue, 22 Sep 2020 20:09:39 GMT HAPServer [b1:e7:dd:4c:20:4a] HAP Request: PUT /characteristics
host.raspberrypi | 2020-09-22 22:09:39.840 | error | Caught by controller[7]: Tue, 22 Sep 2020 20:09:39 GMT EventedHTTPServer [::ffff:192.168.1.51] HTTP request: /characteristics
host.raspberrypi | 2020-09-22 22:09:39.840 | error | Caught by controller[6]: Tue, 22 Sep 2020 20:09:37 GMT EventedHTTPServer [::ffff:192.168.1.51] Sending HTTP event '22.11' with data: {"characteristics":[{"aid":22,"iid":11,"value":0}]}
host.raspberrypi | 2020-09-22 22:09:39.839 | error | Caught by controller[5]: Tue, 22 Sep 2020 20:09:37 GMT EventedHTTPServer [::ffff:192.168.1.51] HTTP Response is finished
host.raspberrypi | 2020-09-22 22:09:39.839 | error | Caught by controller[4]: Tue, 22 Sep 2020 20:09:37 GMT EventedHTTPServer [::ffff:192.168.1.51] Muting event '22.10' notification for this connection since it originated here.
host.raspberrypi | 2020-09-22 22:09:39.838 | error | Caught by controller[3]: Tue, 22 Sep 2020 20:09:37 GMT Accessory [Yahka-0] Setting Characteristic "On" to value 0
host.raspberrypi | 2020-09-22 22:09:39.838 | error | Caught by controller[3]: Tue, 22 Sep 2020 20:09:37 GMT Accessory [Yahka-0] Processing characteristic set: [{"aid":22,"iid":10,"value":0}]
host.raspberrypi | 2020-09-22 22:09:39.837 | error | Caught by controller[2]: Tue, 22 Sep 2020 20:09:37 GMT HAPServer [b1:e7:dd:4c:20:4a] HAP Request: PUT /characteristics
host.raspberrypi | 2020-09-22 22:09:39.828 | error | Caught by controller[1]: Tue, 22 Sep 2020 20:09:37 GMT EventedHTTPServer [::ffff:192.168.1.51] HTTP request: /characteristics

**Comment by cryptedx** [comment]
### **Ich habe eine neue Vermutung!** 

Es geht weiterhin um das Licht im Wohnbereich. Das ioBroker KNX Objekt wurde noch nie durch ioBroker geschalten, weil ich bis jetzt leider noch nicht dazu gekommen bin eine vis zu erstellen. HomeKit erschien mir fürs Erste am einfachsten und schnellsten für die wichtigsten Funktionen.
Soeben habe ich dann versucht direkt über die Objekte zu schalten und zu dimmen. Das hat einwandfrei funktioniert. Die Status kommen auch sauber an. Danach habe ich es wieder mit yahka versucht. Siehe da, es funktioniert.
So wie es aussieht, kommt yahka mit jungfräulichen Objekten nicht klar, welche noch nicht geschaltet wurden!

@nicoh88 Wenn du mal die Muse hast, kannst du dir das anschauen? Ich kann zwar etwas python und react native, nur ist mir der Adapter noch zu hoch. Ich finde keinen Ansatz wo ich suchen soll. Vielleicht schaffe ich es in naher Zukunft auch etwas mehr hierzu beizutragen! Danke!

**Comment by cryptedx** [comment]
OK, das ist wirklich Fakt! Ich hab es soeben mit dem Licht im Hobbyraum verifiziert. Yahka kommt mit jungfräulichen Objekten nicht klar.

**Comment by nicoh88** [comment]
> @nicoh88 Wenn du mal die Muse hast, kannst du dir das anschauen? Ich kann zwar etwas python und react native, nur ist mir der Adapter noch zu hoch. Ich finde keinen Ansatz wo ich suchen soll. Vielleicht schaffe ich es in naher Zukunft auch etwas mehr hierzu beizutragen! Danke!

Würde gerne helfen, bin aber leider auch kein Programmierer und wüsste auch nicht wo ich Ansätzen soll. Ich versuche hier nur etwas _Struktur_ reinzubringen. Sorry.

**Comment by cryptedx** [comment]
Achso, alles klar. Ich denke, dass ich es die nächste 1-2 Monate versuchen werde. Habe leider nicht so viel Zeit.

Danke für deinen Support bzgl. Struktur!

**Comment by cryptedx** [comment]
@nicoh88 Kannst du das bitte als Bug einstufen?

**Comment by jensweigele** [comment]
@cryptedx könntest du das bitte mal mit dem aktuellen Master testen?

**Comment by cryptedx** [comment]
Danke das du dich darum gekümmert hast. Leider habe ich Home Kit bei mir komplett abgerissen. Ich verwende nun Jarvis. Hatte es zum Glück nur deaktiviert. Bin nun auf Version 0.12.0 und es crashed immer noch. Hier mein Log:

```

2020-11-22 11:35:51.649 - error: yahka.0 (26907) uncaught exception: Cannot read property 'val' of null
--
2020-11-22 11:35:51.664 - error: yahka.0 (26907) TypeError: Cannot read property 'val' of null
at /opt/iobroker/node_modules/iobroker.yahka/main.js:2659:37
at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-11-22 11:35:51.666 - info: yahka.0 (26907) cleaning up ...
2020-11-22 11:35:51.668 - info: yahka.0 (26907) cleaned up ...
2020-11-22 11:35:51.682 - info: yahka.0 (26907) terminating
2020-11-22 11:35:51.685 - info: yahka.0 (26907) Terminated (NO_ERROR): Without reason
2020-11-22 11:35:52.243 - info: host.raspberrypi instance system.adapter.yahka.0 terminated with code 0 (NO_ERROR)
2020-11-22 11:35:52.250 - info: host.raspberrypi Restart adapter system.adapter.yahka.0 because enabled
```

**Comment by jensweigele** [comment]
Danke für deine Mühe!
Kannst du nochmal den aktuellen Master testen?
Hatte eine Stelle übersehen.

**Comment by cryptedx** [comment]
Gerne doch.

Du hast es behoben! Yahka stürzt nicht mehr ab.

Besten Dank!

**Comment by andremueller83** [comment]
Hallo in die Runde,
ich habe das selbe Problem. Wie komme ich denn aktuell an die Version 0.12.0? Wie kann ich die auf meinem raspberry installieren?
VG, André

**Comment by andremueller83** [comment]
Habs gefunden - es funktioniert wunderbar!!!
