### ISSUE TITLE
Hue Issuse

### ISSUE THREAD

**Issue by andjandre** [jensweigele/ioBroker.yahka#23]
Hey,
I love your work, but I have the issue, that I can't set a value (Hue) conversion for Hue or other Lightbulbs.

Also I have the Issue, that whenever I change Color Values in the Home App, the only edited values are hue. Saturation would need to be changed aswell but it doesn't. 

<img width="836" alt="bildschirmfoto 2017-12-28 um 16 56 32" src="https://user-images.githubusercontent.com/34341473/34415672-49f94854-ebf0-11e7-803b-e76a8536b64a.png">

**Comment by jensweigele** [comment]
Hi,

could you please try 0.6.0-beta.1 (install it via git: https://github.com/jensweigele/iobroker.yahka-dist) or via the npm beta package.
There you have other conversion functions for the hue as well as an improved hue support.
Since I don't have a hue, it is maybe better to ask in the ioBroker forum for support. There are people who got the Hue running with this connector.

I'll close the issue now - feel free to reopen it if there is something I can do.
