### ISSUE TITLE
Activation of Lightbulbs by a HUE Smart Button is not recognized in Apple's Home App

### ISSUE THREAD

**Issue by Elonil** [jensweigele/ioBroker.yahka#257]
Hello there!

I have noticed that when I turn a light bulb on by pushing the HUE Smart Button, the "On State" of the lightbulb is not detected. Whenever I turn on the light via the HUE Smart Button, Apple's Home App tells me that the lightbulb is still off. When the light is then turned on via the Home App the App shows me that the light bulb is activated and it shows the correct brightness level. If the light is now turned off over the HUE Smart Button then this is correctly detected and the light is shown as "Off" within the Home App.

I created a Node-Red script which allows me to use HomeKit as well as the ioBroker's user interface Lovelace UI. Instead of referring to the "On State" (e.g. lightbulb.action.on) over the hue extended adapter, I created my own "On State". This needs to be done because otherwise I have some problems with the corresponding brightness of the lights, since last brightness states aren't saved anywhere and the lightbulb goes straight to full brightness after it has been turned on via the Home App.

Another point I noticed is that the adapter automatically sets the brightness level to 100% when the "On State" is activated. Is there a way to set a more convenient brightness level directly instead of writing a script?

Best regards
Elonil

**Comment by Videonisse** [comment]
I think your problem is not related to Yahka or Homekit, they do not influence the Brightness setting when On or Off is activated. 

You can verify this if you create two dummy data points in 0_Userdata, one with type number and one boolean. Then connect them to your Lightbulb service in Yahka. Then you can see that the previous brightness % setting will not change in the data point when you switch the Lightbulb on or off. Restoring the last brightness level should be done in the physical device, what kind of lightbulb do you actually have? I have the low-cost Ikea and they support this.

**Comment by Elonil** [comment]
I am using Philips Hue Lightbulbs in my appartment. When I set the On State via the "on" variable in the hue-extended.0 parameter list, then the last state is activated. When I change this state within yahka over the "On" Service, then the light is set to 100%. What else should it be instead of the yahka adapter? I don't know what else it should be. If it would have been the hue extended adapter then the light wouldn't turn back on to its last known brightness state.

**Comment by Elonil** [comment]
I reinstalled all adapters and everything works fine now. I don't know what the exact problem was but now everything works just fine.
