### ISSUE TITLE
KNX Rolläden - Status (schließen und wird geöffnet9

### ISSUE THREAD

**Issue by andremueller83** [jensweigele/ioBroker.yahka#259]
Hallo in die Runde,
ich habe schon mehrere Foren und Beiträge zu meinem Problem gelesen aber noch keine entsprechende Lösung gefunden.
Ich steuere meine Rolladen über KNX und dem YAHKA Adapter. Bis auf folgenden Problem läuft auch alles wunderbar.

Betätige ich meine Glastaster an der Wand bzw. kommt der Impuls zum Verändern der Rolladenposition über den KNX Bus steht bei der Rollade im Homekit danach immer ("schließen" bzw. wird "geöffnet"). 

Ich habe in einem Beitrag von Jens gelesen das der "Position State" diesen Stati erzeugt.

https://github.com/jensweigele/ioBroker.yahka/issues/216

0 - herunterfahren
1 - hochfahren
2 - steht

Ich habe für den Position State mal ein separates Objekt im ioBroker angelegt, in welches ich die Werte 0,1 oder 2 reinschreibe, Leider ändert sind der Status der Anzeige nicht und bleibt weiterhin auf "wird geöffnet" oder "schließen" stehen.

Wo habe ich einen Denkfehler?

![image](https://user-images.githubusercontent.com/70439951/114041112-8803fd80-9884-11eb-8343-5b893c4bdbe3.png)

**Comment by Videonisse** [comment]
Have you tried to instead leave out PositionState from the Yahka config? 

As I wrote in Issue# 255, PositionState is calculated automatically if it is not included in Yahka. Actually, according to the Apple HAP spec, it should be "mandatory", but either it can still be omitted, or there is some hidden function in hap-nodejs/Yahka where it fills in the correct value based on Target and Current when it's missing.

Anyway, if you haven't yet, try it out.

https://github.com/jensweigele/ioBroker.yahka/issues/255

**Comment by andremueller83** [comment]
Klasse es funktioniert. Der Hinweis das der Status automatisch berechnet wird war gold wert. Ich hatte vor einigen Wochen auch schon den Status "Target Position" leer gelassen. Damals hatte ich aber scheinbar die falschen Objekte bei Target Position hinterlegt.
Hier die korrekten Einstellungen mit denen die KNX Rolläden mit Yahka fehlerfrei laufen - falls noch jmd dieses Problem hat.

![image](https://user-images.githubusercontent.com/70439951/114079934-0d020d80-98ab-11eb-9d92-67cac3e3427b.png)

**Comment by Videonisse** [comment]
Spitze! The suggestion about multistate has solved my issue with my Rademacher Markisensteuerung. Without it, when using Scenes to position the Awning, it didn't show status for Opened and Closed correctly. This because the Manual (target) position wasn't used/updated, and then had the last used % för manual control and the current position was often something else. 

The only thing I think I can't solve is that when using a scene, the PositionState will not show if it's opening or closing. But this could probably be fixed using a script, but I don't care as long it shows the correct status when it stopped moving.

![image](https://user-images.githubusercontent.com/13684218/114094277-69b9f400-98bc-11eb-90b4-a4c03c323e8f.png)

**Comment by andremueller83** [comment]
Klasse das freut mich :)
