### ISSUE TITLE
HomeKit connection stop working after update from 0.11.0 to 0.12.0

### ISSUE THREAD

**Issue by sysista** [jensweigele/ioBroker.yahka#262]
Yes, homeKit connection stop working after update from 0.11.0 to 0.12.0 it is possible to replicate this behavior.
Need more details?

**Comment by Videonisse** [comment]
Update to latest version first, it's v0.13.1.

**Comment by unstressable** [comment]
The Problem still occurs in 0.14.0.
0.11.0 is the latest that works.
For me the problem starts by using the Fritz!Box guest-LAN-Port. A "normal" LAN-Port worked fine for all versions.

**Comment by Videonisse** [comment]
As I understand it, the problem is that bridging between two VLANs stoped working when Yahka is using Ciao instead of the previous Bonjour implementation in Hap-nodejs. 

Probably related to issue "ciao: Accessories deregistered from Bonjour about 1-2min after launching": https://github.com/homebridge/HAP-NodeJS/issues/856

Also discussed in the Forum: https://forum.iobroker.net/post/618419

**Comment by jensweigele** [comment]
You can activate the "Legacy Advertiser" which could fix your problem.
