### ISSUE TITLE
Air purifier stays "Turning on..."

### ISSUE THREAD

**Issue by janhp** [jensweigele/ioBroker.yahka#275]
Dear Dev,

I have to following problem: When I turn my Air Purifer ON it stays at "Turning ON".

<img width="174" alt="Screenshot 2021-05-21 at 23 12 04" src="https://user-images.githubusercontent.com/71586781/119198813-458c2e00-ba8a-11eb-9e14-5cdb2616eae6.png">

This is my config (changed active to "bool")
<img width="982" alt="Screenshot 2021-05-21 at 23 12 23" src="https://user-images.githubusercontent.com/71586781/119198847-5341b380-ba8a-11eb-9589-8b7cf60b3a83.png">

Thanks a lot for your help!

**Comment by Videonisse** [comment]
You should use the support forum instead of creating an issue here, as it's not a bug nor a feature request.

But as a short reply. The above settings are from the characteristic "Active" I assume? First, I think you should not change the format to boolean because Homekit expect it to be a number and I believe the adapter will automatically convert boolean to number when needed. Second, you need to set the value for CurrentAirPurifierState ("INACTIVE = 0";"IDLE = 1";"PURIFYING_AIR = 2) . Currently, it will be set to Inactive (0) but must be Idle (1) or Purifying Air (2).

![image](https://user-images.githubusercontent.com/13684218/119320344-c8280f80-bc7b-11eb-931e-e1b420d6c7b3.png)

**Comment by janhp** [comment]
thanks that worked!
