### ISSUE TITLE
Update 13.1 -> 17.0: Lost all devices in config

### ISSUE THREAD

**Issue by do1osc** [jensweigele/ioBroker.yahka#410]
After updateing from 13.1 to 17.0, i lost all enties in the config.

Is there a solution for not loosing all configs?

**Comment by TA2k** [comment]
What mean lost.

**Comment by TA2k** [comment]
no group aufklappen

**Comment by do1osc** [comment]
Ahh. Okay. thats okay, but it is all not reachable in home-app since update:
![Bild 22 03 23 um 21 21](https://user-images.githubusercontent.com/45193453/227029491-90f7e32f-515c-45c2-ad36-4d1e461c7f04.jpg)

Any suggestions ?

**Comment by do1osc** [comment]
Found solution: Use ciao

**Comment by Git-Romer** [comment]
Same issue here. 
Setting the mode from default avahi (as I already used in previous version (0.13.1)) to ciao did not seem to fix this.
I am using a docker installation of iobroker running on a raspberry pi and having the avahi env variable set to true in the docker-compose file.

After inspecting the changelog of v0.17.0 it has been stated that default is now avahi. Why is it that now that it is activated by deault, my devices will no longer respond in the HomeKit app?
If I understand correctly for the users who used avahi before nothing should have changed?!

Is there any fix for this issue or will it get fixed in a update?

**Comment by Git-Romer** [comment]
@do1osc could you kindly reopen this ticket?
