### ISSUE TITLE
Support for AirPlay 2 TVs or fakeAppleTV?

### ISSUE THREAD

**Issue by noaboa97** [jensweigele/ioBroker.yahka#89]
I've been using your adapter since a while now and it's just great, I love it!

I want to also integrate my TV what's surely possible with the sony bravia adapter althought it's then only going to be a switch in homekit. 

An enhancement would be to get a service in yahka which imitates the Apple TV so that I would be able to controll it over Homekit or over the Control Center with the Apple TV Remote that would really awesome.

An other enhancement would be a service for TVs in Homekit because Apple is now Officialy going to support AirPlay 2 on TV's so TV's are going to be supportet in HomeKit

Thanks for your consideration

Keep up with your awesome work!

**Comment by noaboa97** [comment]
But couldn't yahka pretend to be an apple tv? to somehow respond to the broadcast the iPhone is making and then respond to that? or how are the apple tv's detected in the network? 
Also not possible with the new feature coming that homekit officially will support tv's?

https://www.apple.com/ios/home/

**Comment by DanielWeeber** [comment]
No. No faking of Airplay2 devices possible - hopefully not yet. Device will not show up in Home App, even if you try. Follow HAP-NodeJS instead of Yahka if you want to get more information.
Airplay2 uses a different protocol than HAP.

**Comment by noaboa97** [comment]
ohh okay to bad. 
Hopefully somebody figures it out!
Thanks :)

**Comment by jensweigele** [comment]
The tv-manufacturers are talking about "HomeKit" and "Airplay2" on the CES (and Samsung for example will not support HomeKit - just AirPlay2).
Maybe the HomeKit protocol will be extended in the next months to include characteristics and services to control a TV - but maybe it's really dealed within the AirPlay2 protocol.

I'll close the ticket for now - reopen it if you have new information ;-)

**Comment by noaboa97** [comment]
Sorry to disturb u again. But apple already writes it on their homepage (only US page) 
That TV‘s will be able to be controlled via homekit.

If u haven‘t seen it check it out.

https://www.apple.com/ios/home/

**Comment by jensweigele** [comment]
I saw it - but unfortunately there are just marketing texts
The apple developer portal says nothing about a homekit change currently.
TV are also not mentioned in the documentation.

**Comment by noaboa97** [comment]
Okay
Thanks :) I will hope for the best.

**Comment by noaboa97** [comment]
So I've just read, that the iOS Beta 12.2 supports TV's and Khaos Tian already released hap-nodejs v0.4.48 and homebridge v0.4.46 with TV Profile Support. Maybe you wanna have a look?

**Comment by DanielWeeber** [comment]
Even though this is correct I am still thinking that you confuse Airplay2 with HomeKit.

**Comment by noaboa97** [comment]
> Even though this is correct I am still thinking that you confuse Airplay2 with HomeKit.

MayBe I do....

**Comment by noaboa97** [comment]
> I just had a look at the hap-nodejs changes.
> It adds Services and Characterstics to **control** the TV (like changing the input source, switching it on, change the volume).
> 
> And I think that is what he means

Yes this is what I mean. 
The I would be possible to controll my TV with HomeKit or with the iOS ATV Remote App what's my goal.

**Comment by DanielWeeber** [comment]
You will not be able to Control it via the Remote App.

Everything you mentioned is not dependend on the implementation of the TV service. This is already possible today. 

The only thing which will change is that you will have a TV symbol instead of lightswitches to control the TV.
You will still need to add your TV via another adapter like ioBroker.lgtv or something similar.

I am also looking forward to this.

**Comment by jensweigele** [comment]
I've updated the hap-nodejs dependency. If you install the latest master, you will see the services "Television", "InputSource" and "VolumeControl". I'm just updating an iPad to 12.2 to check if it works.

**Comment by noaboa97** [comment]
Awesome! How do I install the lastest master? 
Just the normal iobroker CLI command to update an adapter? 
Will my settings/devices stay?

**Comment by jensweigele** [comment]
You need to install the adapter from github. In the admin interface there is a button for it (looks like a cat - the github logo).
There you can select Yahka and update the adapter.

Your settings will remain and if everything works, you should have no problems after the update.
But remember: the master is not "stable" which means, it's more likely to have errors in the master, than in the latest NPM release (that's at least the theory ;-) )

I already saw, that it is not really working with the 12.2 beta. I need to add an ability to link services to each other - otherwise the input source service ist not working.

**Comment by noaboa97** [comment]
Okay thanks, but I'll guess I'll wait until you realease the stable version and also the iOS12.2 is released officially :)

**Comment by besc2de** [comment]
Is there already an example how to map the YAHKA television service properties to ioBroker datapoints? I tried it with the LG WebOS ioBroker adapter but since the YAHKA television service properties do to not directly correlate to the datapoints provided from the LG adapter the integration was not successful. 

Is it possible to turn the TV on/off or changing the volume within this scenatio?

Thanks and best regards

**Comment by noaboa97** [comment]
> 
> 
> Is there already an example how to map the YAHKA television service properties to ioBroker datapoints? I tried it with the LG WebOS ioBroker adapter but since the YAHKA television service properties do to not directly correlate to the datapoints provided from the LG adapter the integration was not successful.
> 
> Is it possible to turn the TV on/off or changing the volume within this scenatio?
> 
> Thanks and best regards

You need to write a script and add a custom datapoint or datapoints. Thats what I did. It works fine for me. 
I can't change the volume just turn it on and off. 
But maybe with the new update of homekit which supports tv's

**Comment by noaboa97** [comment]
@jensweigele 
Are you soon releasing the stable version with tv support? 
otherwise I guess I'll try out the master, is it working fine for you?

**Comment by Donderda** [comment]
Does an example exist how to link InputSources / Volume Control between ioBroker and Homekit?

**Comment by nicoh88** [comment]
Doppelt mit #131?

**Comment by noaboa97** [comment]
> Doppelt mit #131?

Ein Teil überlappt sich.

**Comment by jensweigele** [comment]
The linked services are in a rudimentary state implemented. In my tests I was able to switch between the inputs of my virtual TV.
On the right top corner of a service, you can now select a service to link with.
The Input-Services need to be linked to the TV service.

Caution: renaming the TV service will not update the link. Renaming services in general will not update the combobox so you need to select another device and go back to the device in order to see the correct services list.
To get the TV icon back, you need to publish the device as an own device outside of the bridge. This is located in the "Device Properties". There you need to put in username, pincode etc. in the desired format.
After that you can set the category to "Television", to get the TV icon back.
In your iOS client you need to pair this new devices with your Homekit-System.

As I said: Work in Progress - there will be more validation in the future to avoid wrong data input.  
If you find any issue with the implementation, please create a new ticket!

**Comment by nicoh88** [comment]
https://github.com/jensweigele/ioBroker.yahka/wiki/Fernseher-mit-YAHKA-simulieren
